import { AuditLog } from "@/types/audit";

export const mockAuditLogs: AuditLog[] = [
  {
    id: "log-001",
    timestamp: "2026-03-02T08:30:00Z",
    actor_id: "user-alice",
    actor_name: "Alice Chen",
    action: "cr_created",
    target_cr_id: "cr-001",
    target_cr_title: "Update Stripe SDK to v5 and refactor payment flow",
    details: { repo: "payments-service", branch: "feat/update-stripe-integration" },
    ip_address: "10.0.1.42",
    risk_level: "high",
  },
  {
    id: "log-002",
    timestamp: "2026-03-02T09:15:00Z",
    actor_id: "user-alice",
    actor_name: "Alice Chen",
    action: "cr_submitted",
    target_cr_id: "cr-001",
    target_cr_title: "Update Stripe SDK to v5 and refactor payment flow",
    details: { risk_score: 82 },
    ip_address: "10.0.1.42",
    risk_level: "high",
  },
  {
    id: "log-003",
    timestamp: "2026-03-02T10:00:00Z",
    actor_id: "user-bob",
    actor_name: "Bob Smith",
    action: "cr_approved",
    target_cr_id: "cr-001",
    target_cr_title: "Update Stripe SDK to v5 and refactor payment flow",
    details: { comment: "Looks good, tested on staging." },
    ip_address: "10.0.1.55",
    risk_level: "high",
  },
  {
    id: "log-004",
    timestamp: "2026-03-02T10:30:00Z",
    actor_id: "user-carol",
    actor_name: "Carol Wang",
    action: "cr_created",
    target_cr_id: "cr-002",
    target_cr_title: "Fix session timeout not refreshing on activity",
    details: { repo: "user-service" },
    ip_address: "10.0.1.67",
    risk_level: "low",
  },
  {
    id: "log-005",
    timestamp: "2026-03-02T11:00:00Z",
    actor_id: "user-dave",
    actor_name: "Dave Lee",
    action: "cr_approved",
    target_cr_id: "cr-002",
    target_cr_title: "Fix session timeout not refreshing on activity",
    details: { comment: "LGTM" },
    ip_address: "10.0.1.78",
    risk_level: "low",
  },
  {
    id: "log-006",
    timestamp: "2026-03-02T12:00:00Z",
    actor_id: "user-carol",
    actor_name: "Carol Wang",
    action: "cr_applied",
    target_cr_id: "cr-002",
    target_cr_title: "Fix session timeout not refreshing on activity",
    details: { commit_sha: "b2c3d4e5f6a7" },
    ip_address: "10.0.1.67",
    risk_level: "low",
  },
  {
    id: "log-007",
    timestamp: "2026-03-02T13:00:00Z",
    actor_id: "user-frank",
    actor_name: "Frank Chen",
    action: "cr_changes_requested",
    target_cr_id: "cr-003",
    target_cr_title: "Add bulk CSV import for inventory items",
    details: { comment: "Security issue in CSV parser - path traversal risk." },
    ip_address: "10.0.1.89",
    risk_level: "med",
  },
  {
    id: "log-008",
    timestamp: "2026-03-02T14:00:00Z",
    actor_id: "user-grace",
    actor_name: "Grace Kim",
    action: "policy_updated",
    target_policy_id: "policy-001",
    details: { changes: ["Updated risk thresholds", "Added new path rule for payments/**"] },
    ip_address: "10.0.1.91",
    risk_level: "med",
  },
  {
    id: "log-009",
    timestamp: "2026-03-02T15:30:00Z",
    actor_id: "user-henry",
    actor_name: "Henry Zhang",
    action: "incident_mode_enabled",
    details: { reason: "Production incident detected in payments-service" },
    ip_address: "10.0.1.23",
    risk_level: "high",
  },
  {
    id: "log-010",
    timestamp: "2026-03-02T16:00:00Z",
    actor_id: "user-henry",
    actor_name: "Henry Zhang",
    action: "incident_mode_disabled",
    details: { reason: "Incident resolved", duration_minutes: 30 },
    ip_address: "10.0.1.23",
    risk_level: "med",
  },
];
