import { CR, CRListItem } from "@/types/cr";

export const mockCRs: CR[] = [
  {
    id: "cr-001",
    repo: "payments-service",
    branch: "feat/update-stripe-integration",
    title: "Update Stripe SDK to v5 and refactor payment flow",
    description:
      "This CR upgrades the Stripe SDK from v4 to v5, which includes breaking changes in the payment intent API. Also refactors the payment flow to handle webhook retry logic.",
    created_at: "2026-03-01T08:30:00Z",
    updated_at: "2026-03-01T14:22:00Z",
    created_by: "user-alice",
    created_by_name: "Alice Chen",
    status: "pending_approval",
    risk_score: 82,
    risk_level: "high",
    required_approvals: 2,
    pr_url: "https://github.com/org/payments-service/pull/142",
    commit_sha: "a1b2c3d4e5f6",
    labels: ["payments", "breaking-change", "sdk-upgrade"],
    plan: `## Change Plan\n\n### Overview\nUpgrade Stripe SDK from v4 to v5 and refactor payment processing flow.\n\n### Steps\n1. Update package.json dependency\n2. Migrate PaymentIntent API calls to new format\n3. Update webhook handler for new event structure\n4. Update tests\n\n### Rollback Plan\nRevert to v4 tag: \`git revert a1b2c3d\`\n\n### Risk Assessment\n- **Breaking Changes**: Stripe v5 has breaking API changes\n- **Revenue Impact**: Payment flow modifications could affect revenue\n- **Mitigation**: Feature flag enabled, canary deployment planned`,
    patch_summary: [
      {
        path: "src/payments/stripe.ts",
        additions: 145,
        deletions: 89,
        risk_rules_hit: ["payments/**", "external-sdk-update"],
        risk_level: "high",
      },
      {
        path: "src/payments/webhook.ts",
        additions: 67,
        deletions: 43,
        risk_rules_hit: ["payments/**"],
        risk_level: "high",
      },
      {
        path: "src/payments/types.ts",
        additions: 23,
        deletions: 12,
        risk_rules_hit: [],
        risk_level: "low",
      },
      {
        path: "tests/payments/stripe.test.ts",
        additions: 201,
        deletions: 87,
        risk_rules_hit: [],
        risk_level: "low",
      },
      {
        path: "package.json",
        additions: 2,
        deletions: 2,
        risk_rules_hit: ["package.json"],
        risk_level: "med",
      },
    ],
    blast_radius: {
      nodes: [
        { id: "f1", type: "file", label: "stripe.ts", risk_level: "high" },
        { id: "f2", type: "file", label: "webhook.ts", risk_level: "high" },
        { id: "f3", type: "file", label: "payment-controller.ts", risk_level: "med" },
        { id: "s1", type: "service", label: "payments-service", risk_level: "high" },
        { id: "s2", type: "service", label: "order-service", risk_level: "med" },
        { id: "s3", type: "service", label: "notification-service", risk_level: "low" },
        { id: "d1", type: "database", label: "payments-db", risk_level: "med" },
      ],
      edges: [
        { id: "e1", source: "f1", target: "s1" },
        { id: "e2", source: "f2", target: "s1" },
        { id: "e3", source: "f3", target: "s1" },
        { id: "e4", source: "s1", target: "s2", label: "HTTP" },
        { id: "e5", source: "s1", target: "s3", label: "Event" },
        { id: "e6", source: "s1", target: "d1", label: "SQL" },
      ],
    },
    evidence: [
      { type: "test", status: "passed", name: "Unit Tests", summary: "247/247 tests passing" },
      { type: "test", status: "passed", name: "Integration Tests", summary: "43/43 tests passing" },
      {
        type: "sast",
        status: "warning",
        name: "CodeQL",
        summary: "2 medium findings",
        details: "CWE-89: SQL injection risk in webhook handler (low confidence)",
      },
      { type: "sca", status: "passed", name: "Snyk SCA", summary: "No critical vulnerabilities" },
      { type: "lint", status: "passed", name: "ESLint", summary: "0 errors, 3 warnings" },
    ],
    approvals: [
      {
        id: "ap-1",
        reviewer_id: "user-bob",
        reviewer_name: "Bob Smith",
        action: "approved",
        comment: "Looks good, tested on staging.",
        created_at: "2026-03-01T12:00:00Z",
      },
    ],
  },
  {
    id: "cr-002",
    repo: "user-service",
    branch: "fix/session-timeout",
    title: "Fix session timeout not refreshing on activity",
    description: "Users were being logged out after 30 minutes even when actively using the app.",
    created_at: "2026-03-01T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
    created_by: "user-carol",
    created_by_name: "Carol Wang",
    status: "approved",
    risk_score: 28,
    risk_level: "low",
    required_approvals: 1,
    pr_url: "https://github.com/org/user-service/pull/89",
    commit_sha: "b2c3d4e5f6a7",
    labels: ["bug", "auth"],
    plan: `## Change Plan\n\n### Fix\nUpdate session middleware to reset expiry timer on any authenticated request.`,
    patch_summary: [
      {
        path: "src/middleware/session.ts",
        additions: 12,
        deletions: 5,
        risk_rules_hit: ["src/auth/**"],
        risk_level: "low",
      },
      {
        path: "tests/middleware/session.test.ts",
        additions: 24,
        deletions: 0,
        risk_rules_hit: [],
        risk_level: "low",
      },
    ],
    blast_radius: {
      nodes: [
        { id: "f1", type: "file", label: "session.ts", risk_level: "low" },
        { id: "s1", type: "service", label: "user-service", risk_level: "low" },
        { id: "s2", type: "service", label: "api-gateway", risk_level: "low" },
      ],
      edges: [
        { id: "e1", source: "f1", target: "s1" },
        { id: "e2", source: "s1", target: "s2" },
      ],
    },
    evidence: [
      { type: "test", status: "passed", name: "Unit Tests", summary: "89/89 tests passing" },
      { type: "sast", status: "passed", name: "CodeQL", summary: "No findings" },
      { type: "sca", status: "passed", name: "Snyk SCA", summary: "No vulnerabilities" },
    ],
    approvals: [
      {
        id: "ap-2",
        reviewer_id: "user-dave",
        reviewer_name: "Dave Lee",
        action: "approved",
        comment: "LGTM",
        created_at: "2026-03-01T11:30:00Z",
      },
    ],
  },
  {
    id: "cr-003",
    repo: "inventory-service",
    branch: "feat/bulk-import",
    title: "Add bulk CSV import for inventory items",
    description: "New feature allowing merchants to import up to 10,000 items via CSV upload.",
    created_at: "2026-02-28T15:00:00Z",
    updated_at: "2026-03-01T09:00:00Z",
    created_by: "user-eve",
    created_by_name: "Eve Johnson",
    status: "changes_requested",
    risk_score: 55,
    risk_level: "med",
    required_approvals: 1,
    pr_url: "https://github.com/org/inventory-service/pull/201",
    commit_sha: "c3d4e5f6a7b8",
    labels: ["feature", "import"],
    plan: `## Change Plan\n\n### Overview\nAdd bulk CSV import endpoint with validation and async processing.`,
    patch_summary: [
      {
        path: "src/import/csv-parser.ts",
        additions: 234,
        deletions: 0,
        risk_rules_hit: ["src/import/**"],
        risk_level: "med",
      },
      {
        path: "src/api/inventory.ts",
        additions: 89,
        deletions: 12,
        risk_rules_hit: [],
        risk_level: "low",
      },
      {
        path: "src/workers/import-processor.ts",
        additions: 167,
        deletions: 0,
        risk_rules_hit: ["src/workers/**"],
        risk_level: "med",
      },
    ],
    blast_radius: {
      nodes: [
        { id: "f1", type: "file", label: "csv-parser.ts", risk_level: "med" },
        { id: "f2", type: "file", label: "import-processor.ts", risk_level: "med" },
        { id: "s1", type: "service", label: "inventory-service", risk_level: "med" },
        { id: "d1", type: "database", label: "inventory-db", risk_level: "med" },
        { id: "s2", type: "service", label: "storage-service", risk_level: "low" },
      ],
      edges: [
        { id: "e1", source: "f1", target: "s1" },
        { id: "e2", source: "f2", target: "s1" },
        { id: "e3", source: "s1", target: "d1", label: "SQL" },
        { id: "e4", source: "s1", target: "s2", label: "S3" },
      ],
    },
    evidence: [
      { type: "test", status: "passed", name: "Unit Tests", summary: "156/156 tests passing" },
      {
        type: "sast",
        status: "failed",
        name: "CodeQL",
        summary: "1 high finding",
        details: "Path traversal vulnerability in CSV file handling",
      },
    ],
    approvals: [
      {
        id: "ap-3",
        reviewer_id: "user-frank",
        reviewer_name: "Frank Chen",
        action: "changes_requested",
        comment:
          "Security issue in CSV parser - path traversal risk. Please fix before merge.",
        created_at: "2026-03-01T09:00:00Z",
      },
    ],
  },
  {
    id: "cr-004",
    repo: "api-gateway",
    branch: "infra/rate-limit-update",
    title: "Update rate limiting thresholds for API endpoints",
    description:
      "Adjust rate limits based on traffic analysis. Increase limits for authenticated users.",
    created_at: "2026-02-27T11:00:00Z",
    updated_at: "2026-03-01T16:00:00Z",
    created_by: "user-grace",
    created_by_name: "Grace Kim",
    status: "applied",
    risk_score: 42,
    risk_level: "med",
    required_approvals: 1,
    pr_url: "https://github.com/org/api-gateway/pull/78",
    commit_sha: "d4e5f6a7b8c9",
    labels: ["infra", "performance"],
    plan: `## Change Plan\n\n### Configuration Changes\nUpdate nginx rate limit config and application middleware.`,
    patch_summary: [
      {
        path: "config/rate-limits.yaml",
        additions: 15,
        deletions: 10,
        risk_rules_hit: ["config/**"],
        risk_level: "med",
      },
      {
        path: "src/middleware/rate-limiter.ts",
        additions: 34,
        deletions: 28,
        risk_rules_hit: [],
        risk_level: "low",
      },
    ],
    blast_radius: {
      nodes: [
        { id: "f1", type: "file", label: "rate-limits.yaml", risk_level: "med" },
        { id: "s1", type: "service", label: "api-gateway", risk_level: "med" },
        { id: "s2", type: "external", label: "All API consumers", risk_level: "low" },
      ],
      edges: [
        { id: "e1", source: "f1", target: "s1" },
        { id: "e2", source: "s1", target: "s2" },
      ],
    },
    evidence: [
      {
        type: "test",
        status: "passed",
        name: "Load Tests",
        summary: "Rate limits verified under 10k RPS",
      },
    ],
    approvals: [
      {
        id: "ap-4",
        reviewer_id: "user-henry",
        reviewer_name: "Henry Zhang",
        action: "approved",
        comment: "Thresholds look appropriate based on traffic data.",
        created_at: "2026-02-28T10:00:00Z",
      },
    ],
  },
  {
    id: "cr-005",
    repo: "analytics-service",
    branch: "feat/real-time-dashboard",
    title: "Add real-time metrics streaming to dashboard",
    description: "Implement WebSocket-based real-time metrics streaming.",
    created_at: "2026-03-02T07:00:00Z",
    updated_at: "2026-03-02T07:00:00Z",
    created_by: "user-iris",
    created_by_name: "Iris Park",
    status: "draft",
    risk_score: 35,
    risk_level: "low",
    required_approvals: 1,
    pr_url: "https://github.com/org/analytics-service/pull/312",
    commit_sha: "e5f6a7b8c9d0",
    labels: ["feature", "websocket"],
    plan: `## Change Plan\n\n### Overview\nAdd WebSocket server for real-time metrics push to dashboard clients.`,
    patch_summary: [
      {
        path: "src/websocket/server.ts",
        additions: 189,
        deletions: 0,
        risk_rules_hit: [],
        risk_level: "low",
      },
      {
        path: "src/metrics/collector.ts",
        additions: 67,
        deletions: 23,
        risk_rules_hit: [],
        risk_level: "low",
      },
    ],
    blast_radius: {
      nodes: [
        { id: "f1", type: "file", label: "server.ts", risk_level: "low" },
        { id: "s1", type: "service", label: "analytics-service", risk_level: "low" },
        { id: "s2", type: "service", label: "dashboard-frontend", risk_level: "low" },
      ],
      edges: [
        { id: "e1", source: "f1", target: "s1" },
        { id: "e2", source: "s1", target: "s2", label: "WS" },
      ],
    },
    evidence: [],
    approvals: [],
  },
];

export const mockCRListItems: CRListItem[] = mockCRs.map((cr) => ({
  id: cr.id,
  repo: cr.repo,
  branch: cr.branch,
  title: cr.title,
  created_at: cr.created_at,
  updated_at: cr.updated_at,
  created_by_name: cr.created_by_name,
  status: cr.status,
  risk_score: cr.risk_score,
  risk_level: cr.risk_level,
  approvals_count: cr.approvals.length,
  required_approvals: cr.required_approvals,
  labels: cr.labels,
}));
